### ISSUE TITLE
Label Errors UI Broken

### ISSUE THREAD

**Issue by kdy294** [orangehrm/orangehrm#1544]
**Environment details**
OrangeHRM version: OrangeHRM OS 5.2
OrangeHRM source: https://sourceforge.net/projects/orangehrm
Platform: on my hosting providers web server to use on my companies domain (hope this helps) Shared Hosting
PHP version: 7.4
Database and version: MYSQL 5.7.39-cll-lve

If applicable:
Browser: Chrome

**Describe the bug**
Labels and Buttons don't appear the way they should. All my add buttons display text as (general.add) and text lables appear as (pim.employee_information) instead that should be a heading.

![Capture_12](https://user-images.githubusercontent.com/118638888/202912727-c662e9fb-affc-46cb-87db-bfc6f990b728.PNG)

**Comment by SupperDog** [comment]
Same here. But labels show correctly when visiting by IP address.

**Comment by kdy294** [comment]
That’s so odd. I wonder what is causing that to happen. It makes confusing to use the system at the moment.

**Comment by SupperDog** [comment]
check #1500

**Comment by RajithaKumara** [comment]
Hi @SupperDog , @kdy294 
Is it possible for you to open the developer tool (can use shortcut `Ctrl + Shift + I`) network tab and provide more info like below screenshot;

![Screenshot from 2022-11-21 09-09-28](https://user-images.githubusercontent.com/25487187/202961363-01f7e47f-cbbf-4ce1-939d-d047c01f08fd.png)

Basically, I want to know values of `ETag` header in the response and `If-None-Match` heder in the request header.
We have already applied a fix https://github.com/orangehrm/orangehrm/pull/1530/commits/ee48d3203152b3d6fb61cce82378b202046a5e57 based on input we received in #1500, #1517. This will be fixed in the 5.3 release.

**Comment by SupperDog** [comment]
> We have already applied a fix [ee48d32](https://github.com/orangehrm/orangehrm/commit/ee48d3203152b3d6fb61cce82378b202046a5e57) based on input we received in #1500, #1517. This will be fixed in the 5.3 release.

Hi yes I can see some fix on this issue but node.js on my server is broken I couldn't test those yet. I have fixed this issue by saving the content of /web/index.php/core/i18n/messages to a static file and redirecting it to that static file using .htaccess

**Comment by joelicatajr** [comment]
> Hi @SupperDog , @kdy294 Is it possible for you to open the developer tool (can use shortcut `Ctrl + Shift + I`) network tab and provide more info like below screenshot;
> 
> ![Screenshot from 2022-11-21 09-09-28](https://user-images.githubusercontent.com/25487187/202961363-01f7e47f-cbbf-4ce1-939d-d047c01f08fd.png)
> 
> Basically, I want to know values of `ETag` header in the response and `If-None-Match` heder in the request header. We have already applied a fix [ee48d32](https://github.com/orangehrm/orangehrm/commit/ee48d3203152b3d6fb61cce82378b202046a5e57) based on input we received in #1500, #1517. This will be fixed in the 5.3 release.

I tried the updating the code from api.service.ts detailed in [ee48d32](https://github.com/orangehrm/orangehrm/commit/ee48d3203152b3d6fb61cce82378b202046a5e57) with the proposed changes but the before and after was the same for me and did not resolve the issue. 

`ETag:` "/RveX7hH7+0PZ5+FUVr/pX4WeN/w5Dn7zeeOwHWp+tA="
`If-None-Match:` W/"/RveX7hH7+0PZ5+FUVr/pX4WeN/w5Dn7zeeOwHWp+tA="

Would appreciate any tips on a patch, not sure what the ETA is on 5.3 yet.

Thanks for your help.

**Comment by joelicatajr** [comment]
Just a FYI for anyone else experiencing this problem. I wiped my install and deployed with 5.1 instead of 5.2 to resolve my issue since there doesn't appear to be a conclusive working fix I could find for 5.2.

**Comment by RajithaKumara** [comment]
Hi @joelicatajr 
Sorry to hear this. Thank you all for providing more info to reproduce this issue. This issue will be fixed in OrangeHRM 5.3 release, which will be released at the end of December.

FYI: If you applied this patch [ee48d32](https://github.com/orangehrm/orangehrm/commit/ee48d3203152b3d6fb61cce82378b202046a5e57), you need to build the frontend after setup the code [for development](https://github.com/orangehrm/orangehrm/wiki/5.x-development-guide). Because releases are optimized for production.

**Comment by joelicatajr** [comment]
Thank you, @RajithaKumara! It makes sense that I was missing a step as others seemed to indicate this patch [ee48d32](https://github.com/orangehrm/orangehrm/commit/ee48d3203152b3d6fb61cce82378b202046a5e57) resolved the issue for them. I appreciate the help and I am definitely looking forward to some of the new features in the 5.3 release. I am also glad to hear it may be coming out this month if all goes according to plan.

**Comment by RajithaKumara** [comment]
This issue was fixed in OrangeHRM 5.3. Get the latest build [here](https://sourceforge.net/projects/orangehrm/).

**Comment by sobanakram** [comment]
Hi @RajithaKumara,
I am getting this issue while using OrangeHRM 5.3 in chrome,
It is working fine in Firefox but getting this error when using chrome.

<img width="1440" alt="Screenshot 2023-03-27 at 1 06 56 PM" src="https://user-images.githubusercontent.com/10559510/227879996-18218015-b439-46bb-be04-3ab62d216f8a.png">
